wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1678427849.426361
    t:
      1:
      - 1
      - 5
      - 40
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 40
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.13.11
      8:
      - 1
      - 5
